### ISSUE TITLE
Support for the latest version of NetworkX

### ISSUE THREAD

**Issue by tengdiyouying608** [anthbapt/multixrank#10]
Hi，

Thank you for developing this tool. I am currently using it and finding it very useful. However, the current version only supports NetworkX 2.5, while NetworkX has now been updated to version 3.3. It would be great if you could add support for the latest version of NetworkX.

Thanks again for your work!

Best,
Liyy

**Comment by anthbapt** [comment]
Hello Liyy,

Thank you for using multiXrank, your request makes a lot of sense, I will work on an update of multiXrank to work with the latest version of networkX (3.3). You can expect to have the new version by the end of August.

Best wishes,
Anthony

**Comment by tengdiyouying608** [comment]
Hi,

When will the new version be released?

**Comment by anthbapt** [comment]
Hello,

Multixrank version 0.3 just released (both in Github and Pypi), it should correct all issues.
Sorry for the slow reply, the last few months were very busy.

Best wishes,
Anthony

PS: Let me know if everything is fine

**Comment by tengdiyouying608** [comment]
Hello,
 I have completed the update, and the results are consistent with the previous ones. 
Thank you very much for the update.

Best wishes,
Liyy

**Comment by anthbapt** [comment]
Hello,

Thank you for keeping me up to date. I'm glad that everything is consistent.

Best wishes,
Anthony
