### ISSUE TITLE
Graph type setting in airport config_full.yml file

### ISSUE THREAD

**Issue by Alba-GM** [anthbapt/multixrank#5]
Hi,

I noticed the sample airport config_full.yml file states within the comment preceding the graph type setting: 

"# Graph type: **unweighted/weighted, undirected/directed**"

while according to both the MultiXRank tutorial and the source lib file the 1/0 input values should be given in the order: **undirected/directed, unweighted/weighted**, here the lines of code:

if self.graph_type[0] == '1':  # directed layer 
if self.graph_type[1] == '1':  # weighted layer

I think the comment in the airport config_full.yml sample file may be misleading.

Thanks!
Best,

Alba

**Comment by anthbapt** [comment]
It has been improved in the code and in the documentation.
Thank you for your feedback
