### ISSUE TITLE
How to run LOOCV

### ISSUE THREAD

**Issue by ayeTown** [anthbapt/multixrank#9]
Hey there,
I didn't see in the documentation how to run the RWR LOOCV algorithm. Can you provide a minimal example?
Thanks for your time,
AT

**Comment by anthbapt** [comment]
Hello, I'm sorry for the delay. You can find the code for the LOOCV in the following Github: https://github.com/anthbapt/multixrank-tools in the folder evaluation.

**Comment by anthbapt** [comment]
The code provided in the folder "evaluation" has been made for a multilayer network composed of two multiplex networks. One composed of genes and the other composed of diseases. 
Feel free to send me any further questions to the following email: abaptista@turing.ac.uk
